### ISSUE TITLE
I got opkg installed on latest firmware

### ISSUE THREAD

**Issue by lyuzashi** [Rocka84/pushing-hue#1]
Thanks for detailing your hack of the Hue Bridge. It's been very helpful working on my own. 

I'm planning to do something similar with push, currently investigating options around logread and possibly compiling my own binaries.

In the mean time, I wanted to share how I installed opkg on the latest firmware which has it removed. I see this was one of your TODOs. I also created a non-root account and installed sudo.

- download https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/openwrt-15.05.1-ar71xx-generic-root.squashfs
- install unsquashfs (`brew install squashfs` on mac)
- extract filesystem, `scp squashfs-root/bin/opkg` to Hue Hub
    - `file opkg` will describe interpreter /lib/ld-uClibc.so.0
    - executing on Hub will give error "can't load library 'libc.so.0'"
- follow symlink instructions on Hue Hub from https://blog.andreibanaru.ro/2018/03/27/philips-hue-2-1-enabling-wifi/
	`cd /lib`
	`ln -s libm-1.0.14.so libm.so.0`
	`ln -s libuClibc-1.0.14.so libc.so.0`
	`ln -s libutil-1.0.14.so libutil.so.0`
	`ln -s libdl-1.0.14.so libdl.so.0`
	`ln -s libcrypt-1.0.14.so libcrypt.so.0`
	`ln -s libpthread-1.0.14.so libpthread.so.0`
	`ln -s librt-1.0.14.so librt.so.0`
	`ln -s libuClibc-1.0.14.so libuClibc.so.0`
- also copy across /etc/opkg.conf and /etc/opkg/distfeeds.conf
    - remove "option check_signature 1" from opkg.conf (Compiled packages won't match the custom build signature)
- Setup user account
	`opkg update`
	`opkg install sudo shadow-groupadd shadow-useradd`
	`visudo`
		- delete comment # for "%sudo ALL=(ALL) ALL"
	`groupadd --system sudo`
	`useradd -s /bin/ash -G sudo ben`
	`mkdir /home/ben`
	`chown ben /home/ben`
- Login with new account

**Comment by Rocka84** [comment]
Hi lyuzashi,

thanks for sharing! Unfortunatly I can't confirm this because I'm not using a hue bridge anymore.
Although this hack improved the usability of the bridge, in the end it still wasn't good enough, in my opinion.
I switched to [zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt), which I highly recommend over a modified hue hub.

But keep on hacking! ;-)

**Comment by Rocka84** [comment]
Update: I added a link to this issue so this info isn't lost (see https://github.com/Rocka84/pushing-hue/pull/2).
Thanks again for sharing!
