### ISSUE TITLE
difficulties replicating your result ;-)

### ISSUE THREAD

**Issue by mories76** [Rocka84/pushing-hue#3]
Hi,

I am struggling to locate the big blob ;-)
I can see the version number, some empty bytes.
My guess was that the IV starts at 0x3c

At the end there's that version again.
Where decrypting is have issues with block length, so I must be doing something wrong.

Do you have a hint ?

```
head
00000000  42 53 42 30 30 32 00 02  00 96 27 29 52 65 6c 65  |BSB002....')Rele|
00000010  61 73 65 4d 61 6e 61 67  65 6d 65 6e 74 50 72 6f  |aseManagementPro|
00000020  64 00 00 96 25 10 01 03  00 00 00 00 31 39 33 35  |d...%.......1935|
00000030  31 34 34 30 34 30 00 00  00 00 00 00 c0 92 58 3b  |144040........X;|
00000040  63 63 94 80 c1 cb 34 7b  e5 fe 6c dc c2 6b f7 a8  |cc....4{..l..k..|
00000050  9e 77 5f a5 51 fb 86 a9  fc 6e ca dd 78 13 f5 d0  |.w_.Q....n..x...|
tail
00962530  62 5d 04 65 ee 27 89 85  54 a0 a6 8e 31 bc 81 25  |b].e.'..T...1..%|
00962540  c9 21 7d 1c 9f bd fa 69  10 b2 37 65 00 00 01 c3  |.!}....i..7e....|
00962550  00 fe 00 00 00 00 31 39  33 35 31 34 34 30 34 30  |......1935144040|
00962560  00 00 00 00 00 00 2d 2d  2d 2d 2d 42 45 47 49 4e  |......-----BEGIN|
00962570  20 50 55 42 4c 49 43 20  4b 45 59 2d 2d 2d 2d 2d  | PUBLIC KEY-----|
00962580  0a 4d 49 49 42 49 6a 41  4e 42 67 6b 71 68 6b 69  |.MIIBIjANBgkqhki|
00962590  47 39 77 30 42 41 51 45  46 41 41 4f 43 41 51 38  |G9w0BAQEFAAOCAQ8|
009625a0  41 4d 49 49 42 43 67 4b  43 41 51 45 41 6f 62 71  |AMIIBCgKCAQEAobq|
```

**Comment by mories76** [comment]
A few days a go an update was released. It gave me the opportunity to figure it out.
I was close ;-)

**Comment by Rocka84** [comment]
Hi,
sorry I missed this issue. I'm glad you figured it out! 
I switched to zigbee2mqtt quite some time ago and never looked back, so I can't tell how outdated my findings are by now. 
But you got me curious. May I ask what route you took after gaining access to the hub? Do you use my (or some other) shell script or have you found some other way?

**Comment by mories76** [comment]
No problem,
I am just doing this out of curiosity. Getting root acces was simple.
The url to the firmware update was easily captured by capturing network traffic, by using my mac as a bridge. Binwalk on the firmware didn't give any result.

There are some files on the filesystem which point to encryption.
Key to decrypting the firmware was finding the offset and length of the encrypted piece.

The update script makes use of a log command, so I logged the offset and length and just exited the script before actually upgrading. This was possible because a new firmware was just released.
I can switch bootslot to revert to previous firmware.

No I can decrypt the firmware outside the bridge.
Binwalking the file shows me 93 xz comppessed containers, I can extract them, but I don't see any logic behind that. Yet.. ;-)

My ultimate goal would be to find a source for the firmwares for hue devices like the light and sensors.
Traffic is encrypted, that also needs some further analysis.

Just some random thoughts.

**Comment by mcr-ksh** [comment]
@mories76 Could you share your findings on the offset and length? I'm also doing that exercise to downgrade my image to have wifi tools again. Currently I got stuck at the offset.
